version: "3.9"

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ./back/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./front/.env
    restart: unless-stopped